### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by n0ncetonic** [lanrat/czds#1]
Ran with options `czds-dl -token czdsToken -out ~/czds-zones` I'm getting the following error fairly consistently/daily

`could not download https://czds.icann.org/en/download-zone-data/1337?token=czdsToken : 403 Forbidden (403)`

Visiting the url with valid token I get error `The most recent request for this domain has not been approved.`

Is there any way to convert download id (1337) into a human readable zone so I can re-request? I've tried multiple times to re-request access to any denied/pending zones with no luck.

**Comment by lanrat** [comment]
Unfortunately there is no API to convert the download ID to the zone name. This program gets the zone names from the HTTP headers which are only available on a successful download. You could however log into the CZDS portal to view pending/revoked/expired requests.

That being said, the CZDS API at `https://czds.icann.org/en/user-zone-data-urls.json?token=` should not be returning URLs to files you do not have access to, so this might be a bug. Can you visit the above url with your token and verify that the file you get the 403 error on is listed?

My other project [czds-request](https://github.com/lanrat/czds-request) might help you automatically request zones that have expired ;)

**Comment by n0ncetonic** [comment]
Gonna go ahead and close this issue as my error has been resolved either by [czds-request](https://github.com/lanrat/czds-request) or entropic divine intervention. 

Thanks for pointing me towards czds-request.

```shell
~/czds-request $ ./run.sh
Requested 3 zones:
FIRMDALE, MOSCOW, XN--80ADXHKS

~ $ czds-dl -token Redacted -out ~/czds-zones
found 1422 zones
/Users/user/czds-zones/whoswho.zone.gz downloading
Saved 1422/1422 zones
```
