### ISSUE TITLE
Add version flag for CMDs

### ISSUE THREAD

**Issue by lanrat** [lanrat/czds#15]
Use latest git tag in Makefile.

**Comment by uggyuggy** [comment]
Hi,

thank you for the added `--version`, which make upgrade/testing easier 👍

(side note: It looks this works only when using "git" as sources, not when downloading the the available "tar.gz" in "release" section)
(not complaining at all, just for info)

**Comment by lanrat** [comment]
Go uses git tags for versioning already, I didn't want to introduce a new method that I would need to keep in sync.
