### ISSUE TITLE
Feature request: provide zone download list

### ISSUE THREAD

**Issue by drscream** [lanrat/czds#8]
I know this is a feature request and not a bug report and if I got the understanding of Go I might add a pull request. But for now I will create this as a tracking request if this might be an option to add.

For me, as a user, I would like to download multiple zones provided as a newline or comma separated list. This could be possible by the following options:

```
$ czds-dl -zone ./newline-separated-list
```

or maybe:

```
$ czds-dl -zone example1,example2,example3
```

What do you think as the author of this tool?

**Comment by lanrat** [comment]
Thanks for the suggestion.

You can now pass a list of zones to czds-dl with the `-zone` flag in `v1.0.5`.

To be backwards compatible, I left the flag name `-zone` even though it now support multiple zones.
